/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tmsproject;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;

/**
 *
 * @author Alexandre
 */
public class deletePage extends javax.swing.JFrame {

   int x,y;

   
   private static final String user = "TMS_User";
   private static final String pass = "TMS2022";
   private static final String db = "jbdc:mysql://localhost:3306/tms database";
   
   Connection conn = null;
   PreparedStatement pst = null;
   ResultSet rs = null;
   
   
    public deletePage() {
        initComponents();
        entityMenu.setSelectedItem(null);
        mainPanel.setBackground(new Color(0, 0, 0, 64));
        menuPanel.setBackground(new Color(0, 0, 0, 64));
        addButton.setBackground(new Color(0, 0, 0, 64));
        modifyButton.setBackground(new Color(0, 0, 0, 64));
        deleteButton.setBackground(new Color(0, 0, 0, 64));
        inquireButton.setBackground(new Color(0, 0, 0, 64));
        signoutButton.setBackground(new Color(0, 0, 0, 64));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    /*public void updateDB() {
        try {
            Class.forName("com.mysql.jbdc.Driver");
            conn = DriverManager.getConnection(db, user, pass);
            pst = conn.prepareStatement("select * from tms database");
            
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            q 
        }//END try
    }//END updateDB */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        iconBox = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        entityMenu = new javax.swing.JComboBox<>();
        cCode = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        attributeMenu = new javax.swing.JComboBox<>();
        questionLabel = new javax.swing.JLabel();
        selectAttLabel = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        modifyButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        inquireButton = new javax.swing.JButton();
        signoutButton = new javax.swing.JButton();
        bgPhoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(247, 235, 227));
        bg.setMinimumSize(new java.awt.Dimension(850, 450));
        bg.setPreferredSize(new java.awt.Dimension(860, 500));
        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgMouseDragged(evt);
            }
        });
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconBox.setForeground(new java.awt.Color(255, 255, 255));
        iconBox.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alexandre\\Documents\\GitHub\\TMS\\Images\\citynoBG.png")); // NOI18N
        bg.add(iconBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        exit.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alexandre\\Documents\\GitHub\\TMS\\Images\\icons8-x-24.png")); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        bg.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 0, -1, -1));

        mainPanel.setBackground(new java.awt.Color(247, 235, 227));
        mainPanel.setPreferredSize(new java.awt.Dimension(488, 449));

        entityMenu.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        entityMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Countries", "Province/States", "Locations", "Streets/Roads", "Transportation Custodians", "Transportation Vehicles", "Route Summaries", "Route Details", "Vehicle Maintenance Companies", "Vehicle Maintenance Logs", "Route Schedules", "Reoute Execution Logs", "Road Incidents Logs", "Frequently Asked Questions Log" }));
        entityMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entityMenuActionPerformed(evt);
            }
        });

        cCode.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        submitButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        submitButton.setText("Submit");
        submitButton.setMinimumSize(new java.awt.Dimension(75, 40));
        submitButton.setPreferredSize(new java.awt.Dimension(75, 40));
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        questionLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        questionLabel.setForeground(new java.awt.Color(242, 242, 242));
        questionLabel.setText("What entity would you like to delete?");

        selectAttLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        selectAttLabel.setForeground(new java.awt.Color(242, 242, 242));
        selectAttLabel.setText("Select attribute: ");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(questionLabel)
                        .addGap(60, 60, 60))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectAttLabel)
                            .addComponent(attributeMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(entityMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(cCode, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(entityMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionLabel))
                .addGap(105, 105, 105)
                .addComponent(selectAttLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attributeMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        bg.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 30, 550, -1));

        menuPanel.setPreferredSize(new java.awt.Dimension(260, 434));

        addButton.setBackground(new java.awt.Color(109, 81, 59));
        addButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addButton.setForeground(new java.awt.Color(242, 242, 242));
        addButton.setText("HOME");
        addButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addButton.setPreferredSize(new java.awt.Dimension(39, 40));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        modifyButton.setBackground(new java.awt.Color(109, 81, 59));
        modifyButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        modifyButton.setForeground(new java.awt.Color(242, 242, 242));
        modifyButton.setText("ADD");
        modifyButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modifyButton.setPreferredSize(new java.awt.Dimension(73, 40));
        modifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(109, 81, 59));
        deleteButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(242, 242, 242));
        deleteButton.setText("MODIFY");
        deleteButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteButton.setPreferredSize(new java.awt.Dimension(69, 40));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        inquireButton.setBackground(new java.awt.Color(109, 81, 59));
        inquireButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        inquireButton.setForeground(new java.awt.Color(242, 242, 242));
        inquireButton.setText("INQUIRE");
        inquireButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        inquireButton.setPreferredSize(new java.awt.Dimension(78, 40));
        inquireButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inquireButtonActionPerformed(evt);
            }
        });

        signoutButton.setBackground(new java.awt.Color(109, 81, 59));
        signoutButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        signoutButton.setForeground(new java.awt.Color(242, 242, 242));
        signoutButton.setText("SIGN OUT");
        signoutButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        signoutButton.setPreferredSize(new java.awt.Dimension(78, 40));
        signoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(modifyButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(deleteButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inquireButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
            .addComponent(signoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(modifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(inquireButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(signoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );

        bg.add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 260, 430));

        bgPhoto.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alexandre\\Documents\\GitHub\\TMS\\Images\\citySkylineDark860x500.png")); // NOI18N
        bg.add(bgPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new modifyPage().setVisible(true);
    }//GEN-LAST:event_modifyButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new deletePage().setVisible(true);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void inquireButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inquireButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new inquirePage().setVisible(true);
    }//GEN-LAST:event_inquireButtonActionPerformed

    private void signoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new signoutPage().setVisible(true);
    }//GEN-LAST:event_signoutButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new addPage().setVisible(true);
    }//GEN-LAST:event_addButtonActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_bgMousePressed

    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged
        // TODO add your handling code here:
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);
    }//GEN-LAST:event_bgMouseDragged

    private void entityMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entityMenuActionPerformed
        // TODO add your handling code here:
        try{
            if(entityMenu.getSelectedItem().equals("Countries")) {
                attributeMenu.removeAllItems();
                attributeMenu.addItem("Country Code");
                attributeMenu.addItem("Country Name");
                attributeMenu.addItem("Country Abbreviation");
                attributeMenu.setSelectedItem(null);
            }//END if statement
            else
            if(entityMenu.getSelectedItem().equals("Province/States")) {
                attributeMenu.removeAllItems();
                attributeMenu.addItem("Province Code");
                attributeMenu.addItem("Province Name");
                attributeMenu.addItem("Province Reference Country");
                attributeMenu.setSelectedItem(null);
            }//END if statement
            else
            if(entityMenu.getSelectedItem().equals("Locations")) {
                attributeMenu.removeAllItems();
                attributeMenu.addItem("Location Code");
                attributeMenu.addItem("Location Name");
                attributeMenu.addItem("Location Type (Town, City, or Country)");
                attributeMenu.addItem("Location Reference Province");
                attributeMenu.addItem("Location's Reference Location");
                attributeMenu.setSelectedItem(null);
            }//END if statement
            else
            if(entityMenu.getSelectedItem().equals("Streets/Roads")) {
                attributeMenu.removeAllItems();
                attributeMenu.addItem("Street/Road Code");
                attributeMenu.addItem("Street/Road Name");
                attributeMenu.addItem("Street/Road Distance");
                attributeMenu.addItem("Street/Road Starting Landmark");
                attributeMenu.addItem("Street/Road Ending Landmark");
                attributeMenu.addItem("Street/Road Comment");
                attributeMenu.setSelectedItem(null);
            }//END if statement
            else
            if(entityMenu.getSelectedItem().equals("Transportation Custodians")) {
                attributeMenu.removeAllItems();
                attributeMenu.addItem("Custodian Code");
                attributeMenu.addItem("Custodian First Name");
                attributeMenu.addItem("Custodian Middle Initial");
                attributeMenu.addItem("Custodian Last Name");
                attributeMenu.addItem("Custodian Classification");
                attributeMenu.addItem("Custodian Telephone 1");
                attributeMenu.addItem("Custodian Telephone 2");
                attributeMenu.addItem("Custodian Email");
                attributeMenu.addItem("Custodian Address Street");
                attributeMenu.addItem("Custodian Address Location Code");
                attributeMenu.addItem("Custodian Address Province Code");
                attributeMenu.addItem("Custodian Zip Code");
                attributeMenu.setSelectedItem(null);
            }//END if statement
            else
            if(entityMenu.getSelectedItem().equals("Transportation Vehicles")) {
                attributeMenu.removeAllItems();
                attributeMenu.addItem("Vehicle Code");
                attributeMenu.addItem("Vehicle Descriptive Name");
                attributeMenu.addItem("Vehicle Identification Number");
                attributeMenu.addItem("Vehicle Make");
                attributeMenu.addItem("Vehicle Model");
                attributeMenu.addItem("Vehicle Type");
                attributeMenu.addItem("Vehicle Narrative");
                attributeMenu.setSelectedItem(null);
            }//END if statement
            else
            if(entityMenu.getSelectedItem().equals("Route Summaries")) {
                attributeMenu.removeAllItems();
                attributeMenu.addItem("Route Code");
                attributeMenu.addItem("Route Name");
                attributeMenu.addItem("Route Description");
                attributeMenu.setSelectedItem(null);
            }
            else
            if(entityMenu.getSelectedItem().equals("Route Details")) {
                attributeMenu.removeAllItems();
                attributeMenu.addItem("Route Code");
                attributeMenu.addItem("Street/Road Code");
                attributeMenu.addItem("Final Street/Road Flag");
                attributeMenu.addItem("Distance in Miles");
                attributeMenu.addItem("Distance in Kilometers");
                attributeMenu.setSelectedItem(null);
            }
            else
            if(entityMenu.getSelectedItem().equals("Vehicle Maintenance Companies")) {
                attributeMenu.removeAllItems();
                attributeMenu.addItem("Company Code");
                attributeMenu.addItem("Company Name");
                attributeMenu.addItem("Company Contant Person(s)");
                attributeMenu.addItem("Company Telephone 1");
                attributeMenu.addItem("Company Telephone 2");
                attributeMenu.addItem("Company email");
                attributeMenu.addItem("Company Address Street");
                attributeMenu.addItem("Company Address Location Code");
                attributeMenu.addItem("Company Address Province Code");
                attributeMenu.addItem("Company Zip Code");
                attributeMenu.setSelectedItem(null);
            }
            else
            if(entityMenu.getSelectedItem().equals("Vehicle Maintenance Logs")) {
                attributeMenu.removeAllItems();
                attributeMenu.addItem("VM Code");
                attributeMenu.addItem("Vehicle Maintenance Date");
                attributeMenu.addItem("Vehicle Maintenance Company");
                attributeMenu.addItem("Vehicle Maintenance Mechanic");
                attributeMenu.addItem("Vehicle Maintenance Comment");
                attributeMenu.setSelectedItem(null);
            }
            else
            if(entityMenu.getSelectedItem().equals("Route Schedules")) {
                attributeMenu.removeAllItems();
                attributeMenu.addItem("Route Schedule Code");
                attributeMenu.addItem("Route Schedule Custodian Code");
                attributeMenu.addItem("Route Schedule Vehicle Code");
                attributeMenu.addItem("Route Schedule Assigned Route");
                attributeMenu.addItem("Route Schedule Date");
                attributeMenu.addItem("Route Schedule Comment");
                attributeMenu.setSelectedItem(null);
            }
            else
            if(entityMenu.getSelectedItem().equals("Route Execution Logs")) {
                attributeMenu.removeAllItems();
                attributeMenu.addItem("Route Schedule Code");
                attributeMenu.addItem("Route Schedule Custodian Code");
                attributeMenu.addItem("Route Execution Vehicle Code");
                attributeMenu.addItem("Route Execution Assigned Route");
                attributeMenu.addItem("Route Execution Date");
                attributeMenu.addItem("Route Execution Comment");
                attributeMenu.setSelectedItem(null);
            }
            else
            if(entityMenu.getSelectedItem().equals("Road Incidents Logs")) {
                attributeMenu.removeAllItems();
                attributeMenu.addItem("Incident Code");
                attributeMenu.addItem("Incident Related Custodian Code");
                attributeMenu.addItem("Incident Route Schedule Code");
                attributeMenu.addItem("Incident Comment");
                attributeMenu.setSelectedItem(null);
            }
            else
            if(entityMenu.getSelectedItem().equals("Frequently Asked Questions Log")) {
                attributeMenu.removeAllItems();
                attributeMenu.addItem("Question Code");
                attributeMenu.addItem("Question Text");
                attributeMenu.addItem("Question Response");
                attributeMenu.addItem("Question Comment");
                attributeMenu.setSelectedItem(null);
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_entityMenuActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        String entity = (String) entityMenu.getSelectedItem();
        String atribute = (String) attributeMenu.getSelectedItem();
        
        
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deletePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deletePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deletePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deletePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deletePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JComboBox<String> attributeMenu;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel bgPhoto;
    private javax.swing.JTextField cCode;
    private javax.swing.JButton deleteButton;
    private javax.swing.JComboBox<String> entityMenu;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel iconBox;
    private javax.swing.JButton inquireButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton modifyButton;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JLabel selectAttLabel;
    private javax.swing.JButton signoutButton;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}

